# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('no_of_pages', models.IntegerField()),
                ('date_published', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('dept', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
