# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0002_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_added',
            field=models.DateField(verbose_name=b'auto_now=True, auto_now_add=False'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
