# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0004_auto_20161002_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_published',
            field=models.DateField(),
        ),
    ]
