# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0005_auto_20161002_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
