# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0006_thesis_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Thesis'},
        ),
        migrations.AlterField(
            model_name='thesis',
            name='category',
            field=models.CharField(choices=[(b'Books', b'Books'), (b'Business', b'Business'), (b'Catalogs', b'Catalogs'), (b'Education', b'Education'), (b'Entertainment', b'Entertainment'), (b'Finance', b'Finance'), (b'Food and Drink', b'Food and Drink'), (b'Games', b'Games'), (b'Health and Fitness', b'Health and Fitness'), (b'Lifestyle', b'Lifestyle'), (b'Magazines and Newspaper', b'Magazines and Newspaper'), (b'Medical', b'Medical'), (b'Music', b'Music'), (b'Navigation', b'Navigation'), (b'News', b'News'), (b'Photo and Video', b'Photo and Video'), (b'Productivity', b'Productivity'), (b'Reference', b'Reference'), (b'Shopping', b'Shopping'), (b'Social Networking', b'Social Networking'), (b'Sports', b'Sports'), (b'Travel', b'Travel'), (b'Utilities', b'Utilities'), (b'Weather', b'Weather')], max_length=300),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='dept',
            field=models.CharField(choices=[(b'Accountancy', b'Accountancy'), (b'Banking and Finance', b'Banking and Finance'), (b'Management', b'Management'), (b'Marketing', b'Marketing'), (b'Customs Administration', b'Customs Administration'), (b'Hospitality Management', b'Hospitality Management'), (b'Filipino', b'Filipino'), (b'English and Foreign Language', b'English and Foreign Language'), (b'Physical Education', b'Physical Education'), (b'Social Science', b'Social Science'), (b'Chemical Engineering', b'Chemical Engineering'), (b'Civil Engineering', b'Civil Engineering'), (b'Computer Engineering', b'Computer Engineering'), (b'Electrical Engineering', b'Electrical Engineering'), (b'Electronics Engineering', b'Electronics Engineering'), (b'Industrial Engineering', b'Industrial Engineering'), (b'Mechanical Engineering', b'Mechanical Engineering'), (b'Mining, Geology, and Ceramics Engineering', b'Mining, Geology, and Ceramics Engineering'), (b'Biology', b'Biology'), (b'Chemistry', b'Chemistry'), (b'Computer Science', b'Computer Science'), (b'Mathematics', b'Mathematics'), (b'Psychology', b'Psychology'), (b'Information Technology and Management', b'Information Technology and Management')], max_length=300),
        ),
    ]
