# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0007_auto_20161005_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='dept',
            field=models.CharField(choices=[(b'Accountancy', b'Accountancy'), (b'Banking and Finance', b'Banking and Finance'), (b'Biology', b'Biology'), (b'Chemical Engineering', b'Chemical Engineering'), (b'Chemistry', b'Chemistry'), (b'Civil Engineering', b'Civil Engineering'), (b'Computer Engineering', b'Computer Engineering'), (b'Computer Science', b'Computer Science'), (b'Customs Administration', b'Customs Administration'), (b'Electrical Engineering', b'Electrical Engineering'), (b'Electronics Engineering', b'Electronics Engineering'), (b'English and Foreign Language', b'English and Foreign Language'), (b'Filipino', b'Filipino'), (b'Hospitality Management', b'Hospitality Management'), (b'Industrial Engineering', b'Industrial Engineering'), (b'Information Technology and Management', b'Information Technology and Management'), (b'Management', b'Management'), (b'Marketing', b'Marketing'), (b'Mathematics', b'Mathematics'), (b'Mechanical Engineering', b'Mechanical Engineering'), (b'Mining, Geology, and Ceramics Engineering', b'Mining, Geology, and Ceramics Engineering'), (b'Physical Education', b'Physical Education'), (b'Psychology', b'Psychology'), (b'Social Science', b'Social Science')], max_length=300),
        ),
    ]
