# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcsproject', '0008_auto_20161005_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='desc',
            field=models.TextField(),
        ),
    ]
